### PR TITLE
Adding Hashicorp Vault Addon

### PR DESCRIPTION
**Pull request by atifhafeez**
*Issue #120*

*Added new addon "Hashicorp Vault" based on the existing structure of the repo i.e. 

chart
├── templates
│        └── vault.yaml      **<-- New**
├── values.yaml         **<-- Updated**

add-ons
├── vault                    **<-- New**
│   └── Chart.yaml     **<-- New**
│   └── values.yaml    **<-- New**
*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by atifhafeez** [comment]
@bryantbiggs Kindly advise if we can add hashicorp vault as an addon.

**Comment by atifhafeez** [comment]
@askulkarni2 @kahirokunn @kcaws @florentio

**Comment by atifhafeez** [comment]
@Zvikan can you please review and approve this app?

**Review by nouman2ahmed — APPROVED** [review]

**Comment by Zvikan** [comment]
Ack, going to spin up the [Argo example](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/gitops/argocd), enable vault and test it with your addons fork.
Will update once testing completed

**Comment by atifhafeez** [comment]
Sure, Thank you!

Note: the vault pod will not come up until it is initialized. You already know it ofcourse, but i am documenting it here anyway.

kubectl -n <namespace> exec -ti <name of vault pod> -- vault operator init

**Comment by Zvikan** [comment]
> Sure, Thank you!
> 
> Note: the vault pod will not come up until it is initialized. You already know it ofcourse, but i am documenting it here anyway.
> 
> kubectl -n exec -ti -- vault operator init

@atifhafeez  Following up on this, everything seems to work besides the `vault-agent-injector-cfg` MutatingWebhookConfiguration which is consistent out of sync, it may be related to https://github.com/argoproj/argo-cd/issues/4326  where folks added ignore diff for it.
Did you face this before? how did you resolve it?

**Comment by atifhafeez** [comment]
> vault-agent-injector-cfg

I have faced this issue with multiple apps from this repo and in general. I didn't look into this as of now. Currently, I was focusing on deploying the setup. I am going to look into this during the next couple of days.

Regards!

**Review by Zvikan — APPROVED** [review]
LGTM, we can look into the `MutatingWebhookConfiguration` later on (either add ignore diff or something else).

**Pull request merged**
