### PR TITLE
chore(Cilium values): add enableHubbleUi flag

### PR DESCRIPTION
**Pull request by kahirokunn**

### CODE REVIEW

**Comment by kahirokunn** [comment]
@bryantbiggs I have adjusted it so that users can customize it to their own needs.
How about this?

**Comment by bryantbiggs** [comment]
@kahirokunn users can adjust it to their own needs today by using the project as intended. Users are encouraged to fork this project and make any customizations necessary for their desired outcome, we don't need to code all the various possibilities through this project for all users

**Comment by kahirokunn** [comment]
@bryantbiggs Can't some people, such as myself, contribute to code many frequent cases and satisfy the users?
I want to make this project better.
I am sure there are others who think so.

**Comment by kahirokunn** [comment]
@bryantbiggs hello 👀

**Comment by kahirokunn** [comment]
@bryantbiggs hello 👀

**Comment by bryantbiggs** [comment]
https://github.com/aws-samples/eks-blueprints-add-ons/pull/107#issuecomment-1297501053

**Pull request closed without merging**
