### PR TITLE
chore: ALB helm parameters are already expanded with helm values, so they are not needed

### PR DESCRIPTION
**Pull request by kahirokunn**
set as https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/840

### CODE REVIEW

**Review by bryantbiggs — APPROVED** [review]

**Comment by kahirokunn** [comment]
@bryantbiggs https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/847
I would like to create a PR, can you please comment on this Issue?

**Comment by bryantbiggs** [comment]
as my colleague has stated, values are not passed through Terraform but should be provided by values files in the users gitops manifest repo

**Comment by kahirokunn** [comment]
@bryantbiggs How should the aws resource arn be passed to k8s annotations?

**Comment by kahirokunn** [comment]
Since terraform manages the aws resources, terraform should provide the aws resource arn.
If everything should be managed by git ops, then the irsa module should not follow that policy.

**Comment by bryantbiggs** [comment]
there are numerous ways to handle it - you can use the GitHub provider and write a values file back to the manifest repo for example. the current structure is setup to pass the minimum amount of information required from the `terraform-aws-eks-blueprints` repo to the GitOps controller

**Comment by kahirokunn** [comment]
Thx! I got it.
I will try it once.

**Pull request merged**
